version: '3'
services:
  redis:
    image: redis
    expose:
      - 6379
    networks:
      - backend

  db:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_DB: freefeed
      POSTGRES_USER: freefeed
      POSTGRES_PASSWORD: freefeed
    expose:
      - 5432
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - backend

  init-db:
    image: freefeed/base:latest
    command: node_modules/.bin/knex migrate:latest
    volumes:
      - ./freefeed-server:/server
    working_dir: /server
    environment:
      NODE_ENV: development
    depends_on:
      - db
    networks:
      - backend

  server:
    image: freefeed/base:latest
    command: npm start
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./freefeed-server:/server
    working_dir: /server
    environment:
      NODE_ENV: development
      REDIS_HOST: redis
      PEPYATKA_SERVER_PORT: 3000
    depends_on:
      - redis
      - db
    networks:
      - backend
      - frontend

  client:
    image: freefeed/base:latest
    command: npm start
    ports:
      - 3333:3333
    volumes:
      - ./freefeed-react-client:/client
    working_dir: /client
    environment:
      NODE_ENV: development
    depends_on:
      - server
    networks:
      - frontend

  # nginx:
  #   image: nginx:latest
  #   volumes:
  #     - ./freefeed-react-client:/client
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #   ports:
  #     - 8080:80
  #   depends_on:
  #     - server
  #   networks:
  #     - frontend

networks:
  backend:
  frontend:

volumes:
  dbdata:
